name: Playwright Tests
on:
  push:
    branches: [main]
    # whenever ther is a push to main branch - run tests
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: action/checkout@v2
      - name: Say hello
        run: echo Hello
